# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'segsAdmin.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SEGSAdminTool(object):
    def setupUi(self, SEGSAdminTool):
        SEGSAdminTool.setObjectName("SEGSAdminTool")
        SEGSAdminTool.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(SEGSAdminTool)
        self.centralwidget.setObjectName("centralwidget")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(510, 10, 281, 81))
        self.logo.setObjectName("logo")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 80, 781, 291))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 181, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.runDBTool = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.runDBTool.setEnabled(True)
        self.runDBTool.setMinimumSize(QtCore.QSize(0, 23))
        self.runDBTool.setMaximumSize(QtCore.QSize(16777215, 71))
        self.runDBTool.setObjectName("runDBTool")
        self.verticalLayout_2.addWidget(self.runDBTool)
        self.createUser = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.createUser.setMinimumSize(QtCore.QSize(0, 23))
        self.createUser.setMaximumSize(QtCore.QSize(16777215, 71))
        self.createUser.setObjectName("createUser")
        self.verticalLayout_2.addWidget(self.createUser)
        self.pleasewait = QtWidgets.QLabel(self.tab)
        self.pleasewait.setGeometry(QtCore.QRect(230, 200, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.pleasewait.setFont(font)
        self.pleasewait.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pleasewait.setAlignment(QtCore.Qt.AlignCenter)
        self.pleasewait.setObjectName("pleasewait")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.serverstatus = QtWidgets.QLabel(self.centralwidget)
        self.serverstatus.setGeometry(QtCore.QRect(120, 20, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.serverstatus.setFont(font)
        self.serverstatus.setObjectName("serverstatus")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 3, 95, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.authserver_start = QtWidgets.QPushButton(self.layoutWidget)
        self.authserver_start.setObjectName("authserver_start")
        self.verticalLayout.addWidget(self.authserver_start)
        self.authserver_stop = QtWidgets.QPushButton(self.layoutWidget)
        self.authserver_stop.setObjectName("authserver_stop")
        self.verticalLayout.addWidget(self.authserver_stop)
        self.onlineplayers = QtWidgets.QLabel(self.centralwidget)
        self.onlineplayers.setGeometry(QtCore.QRect(120, 40, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.onlineplayers.setFont(font)
        self.onlineplayers.setObjectName("onlineplayers")
        self.output = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(10, 380, 781, 171))
        self.output.setAutoFillBackground(False)
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        SEGSAdminTool.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SEGSAdminTool)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        SEGSAdminTool.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SEGSAdminTool)
        self.statusbar.setObjectName("statusbar")
        SEGSAdminTool.setStatusBar(self.statusbar)

        self.retranslateUi(SEGSAdminTool)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SEGSAdminTool)

    def retranslateUi(self, SEGSAdminTool):
        _translate = QtCore.QCoreApplication.translate
        SEGSAdminTool.setWindowTitle(_translate("SEGSAdminTool", "SEGSAdminTool"))
        self.logo.setText(_translate("SEGSAdminTool", "<html><head/><body><p><img src=\":/segsLogo/title_v2.png\"/></p></body></html>"))
        self.runDBTool.setText(_translate("SEGSAdminTool", "Create Databases"))
        self.createUser.setToolTip(_translate("SEGSAdminTool", "<html><head/><body><p>Adds a new user account</p></body></html>"))
        self.createUser.setText(_translate("SEGSAdminTool", "Add User Account"))
        self.pleasewait.setText(_translate("SEGSAdminTool", "Please Wait..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SEGSAdminTool", "Databases"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("SEGSAdminTool", "Server Settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("SEGSAdminTool", "Logging"))
        self.serverstatus.setText(_translate("SEGSAdminTool", "placeholder for server status text"))
        self.authserver_start.setText(_translate("SEGSAdminTool", "Start Auth Server"))
        self.authserver_stop.setText(_translate("SEGSAdminTool", "Stop Auth Server"))
        self.onlineplayers.setText(_translate("SEGSAdminTool", "placeholder for number of online players"))
        self.output.setPlainText(_translate("SEGSAdminTool", "Placeholder for console feedback (if needed... could get away with how it is now with command prompt / terminal)"))


