namespace cpp StickWorld
namespace ruby StickWorld

struct ChatMessage {
    1: required i64 source_id;
    2: required i64 timestamp;
    3: required string message;
}
service GameServer
{
    i32 login(string login,string passw), // returns >0 value if login succeeded
}
service ChatServer
{
    void subscribe(i64 my_id),
    oneway void publish(ChatMessage x),
    void unsubscribe(i64 my_id),
}
service ChatClient
{
    oneway void notify(1:ChatMessage x), // called by server
}
